package com.test.manage.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table company
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table company
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table company
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   company
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameIsNull() {
            addCriterion("company_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameIsNotNull() {
            addCriterion("company_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameEqualTo(String value) {
            addCriterion("company_user_name =", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameNotEqualTo(String value) {
            addCriterion("company_user_name <>", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameGreaterThan(String value) {
            addCriterion("company_user_name >", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_user_name >=", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameLessThan(String value) {
            addCriterion("company_user_name <", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameLessThanOrEqualTo(String value) {
            addCriterion("company_user_name <=", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameLike(String value) {
            addCriterion("company_user_name like", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameNotLike(String value) {
            addCriterion("company_user_name not like", value, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameIn(List<String> values) {
            addCriterion("company_user_name in", values, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameNotIn(List<String> values) {
            addCriterion("company_user_name not in", values, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameBetween(String value1, String value2) {
            addCriterion("company_user_name between", value1, value2, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyUserNameNotBetween(String value1, String value2) {
            addCriterion("company_user_name not between", value1, value2, "companyUserName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameIsNull() {
            addCriterion("company_short_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameIsNotNull() {
            addCriterion("company_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameEqualTo(String value) {
            addCriterion("company_short_name =", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameNotEqualTo(String value) {
            addCriterion("company_short_name <>", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameGreaterThan(String value) {
            addCriterion("company_short_name >", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_short_name >=", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameLessThan(String value) {
            addCriterion("company_short_name <", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameLessThanOrEqualTo(String value) {
            addCriterion("company_short_name <=", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameLike(String value) {
            addCriterion("company_short_name like", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameNotLike(String value) {
            addCriterion("company_short_name not like", value, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameIn(List<String> values) {
            addCriterion("company_short_name in", values, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameNotIn(List<String> values) {
            addCriterion("company_short_name not in", values, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameBetween(String value1, String value2) {
            addCriterion("company_short_name between", value1, value2, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyShortNameNotBetween(String value1, String value2) {
            addCriterion("company_short_name not between", value1, value2, "companyShortName");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceIsNull() {
            addCriterion("company_province is null");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceIsNotNull() {
            addCriterion("company_province is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceEqualTo(String value) {
            addCriterion("company_province =", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceNotEqualTo(String value) {
            addCriterion("company_province <>", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceGreaterThan(String value) {
            addCriterion("company_province >", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("company_province >=", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceLessThan(String value) {
            addCriterion("company_province <", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceLessThanOrEqualTo(String value) {
            addCriterion("company_province <=", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceLike(String value) {
            addCriterion("company_province like", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceNotLike(String value) {
            addCriterion("company_province not like", value, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceIn(List<String> values) {
            addCriterion("company_province in", values, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceNotIn(List<String> values) {
            addCriterion("company_province not in", values, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceBetween(String value1, String value2) {
            addCriterion("company_province between", value1, value2, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyProvinceNotBetween(String value1, String value2) {
            addCriterion("company_province not between", value1, value2, "companyProvince");
            return (Criteria) this;
        }

        public Criteria andCompanyCityIsNull() {
            addCriterion("company_city is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCityIsNotNull() {
            addCriterion("company_city is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCityEqualTo(String value) {
            addCriterion("company_city =", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityNotEqualTo(String value) {
            addCriterion("company_city <>", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityGreaterThan(String value) {
            addCriterion("company_city >", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityGreaterThanOrEqualTo(String value) {
            addCriterion("company_city >=", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityLessThan(String value) {
            addCriterion("company_city <", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityLessThanOrEqualTo(String value) {
            addCriterion("company_city <=", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityLike(String value) {
            addCriterion("company_city like", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityNotLike(String value) {
            addCriterion("company_city not like", value, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityIn(List<String> values) {
            addCriterion("company_city in", values, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityNotIn(List<String> values) {
            addCriterion("company_city not in", values, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityBetween(String value1, String value2) {
            addCriterion("company_city between", value1, value2, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyCityNotBetween(String value1, String value2) {
            addCriterion("company_city not between", value1, value2, "companyCity");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictIsNull() {
            addCriterion("company_district is null");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictIsNotNull() {
            addCriterion("company_district is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictEqualTo(String value) {
            addCriterion("company_district =", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictNotEqualTo(String value) {
            addCriterion("company_district <>", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictGreaterThan(String value) {
            addCriterion("company_district >", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("company_district >=", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictLessThan(String value) {
            addCriterion("company_district <", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictLessThanOrEqualTo(String value) {
            addCriterion("company_district <=", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictLike(String value) {
            addCriterion("company_district like", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictNotLike(String value) {
            addCriterion("company_district not like", value, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictIn(List<String> values) {
            addCriterion("company_district in", values, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictNotIn(List<String> values) {
            addCriterion("company_district not in", values, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictBetween(String value1, String value2) {
            addCriterion("company_district between", value1, value2, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyDistrictNotBetween(String value1, String value2) {
            addCriterion("company_district not between", value1, value2, "companyDistrict");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNull() {
            addCriterion("company_address is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIsNotNull() {
            addCriterion("company_address is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressEqualTo(String value) {
            addCriterion("company_address =", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotEqualTo(String value) {
            addCriterion("company_address <>", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThan(String value) {
            addCriterion("company_address >", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("company_address >=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThan(String value) {
            addCriterion("company_address <", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLessThanOrEqualTo(String value) {
            addCriterion("company_address <=", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressLike(String value) {
            addCriterion("company_address like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotLike(String value) {
            addCriterion("company_address not like", value, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressIn(List<String> values) {
            addCriterion("company_address in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotIn(List<String> values) {
            addCriterion("company_address not in", values, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressBetween(String value1, String value2) {
            addCriterion("company_address between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyAddressNotBetween(String value1, String value2) {
            addCriterion("company_address not between", value1, value2, "companyAddress");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIsNull() {
            addCriterion("company_contact is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIsNotNull() {
            addCriterion("company_contact is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactEqualTo(String value) {
            addCriterion("company_contact =", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactNotEqualTo(String value) {
            addCriterion("company_contact <>", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactGreaterThan(String value) {
            addCriterion("company_contact >", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactGreaterThanOrEqualTo(String value) {
            addCriterion("company_contact >=", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactLessThan(String value) {
            addCriterion("company_contact <", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactLessThanOrEqualTo(String value) {
            addCriterion("company_contact <=", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactLike(String value) {
            addCriterion("company_contact like", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactNotLike(String value) {
            addCriterion("company_contact not like", value, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIn(List<String> values) {
            addCriterion("company_contact in", values, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactNotIn(List<String> values) {
            addCriterion("company_contact not in", values, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactBetween(String value1, String value2) {
            addCriterion("company_contact between", value1, value2, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactNotBetween(String value1, String value2) {
            addCriterion("company_contact not between", value1, value2, "companyContact");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelIsNull() {
            addCriterion("company_contact_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelIsNotNull() {
            addCriterion("company_contact_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelEqualTo(String value) {
            addCriterion("company_contact_tel =", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelNotEqualTo(String value) {
            addCriterion("company_contact_tel <>", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelGreaterThan(String value) {
            addCriterion("company_contact_tel >", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelGreaterThanOrEqualTo(String value) {
            addCriterion("company_contact_tel >=", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelLessThan(String value) {
            addCriterion("company_contact_tel <", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelLessThanOrEqualTo(String value) {
            addCriterion("company_contact_tel <=", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelLike(String value) {
            addCriterion("company_contact_tel like", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelNotLike(String value) {
            addCriterion("company_contact_tel not like", value, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelIn(List<String> values) {
            addCriterion("company_contact_tel in", values, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelNotIn(List<String> values) {
            addCriterion("company_contact_tel not in", values, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelBetween(String value1, String value2) {
            addCriterion("company_contact_tel between", value1, value2, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactTelNotBetween(String value1, String value2) {
            addCriterion("company_contact_tel not between", value1, value2, "companyContactTel");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardIsNull() {
            addCriterion("company_contact_id_card is null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardIsNotNull() {
            addCriterion("company_contact_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardEqualTo(String value) {
            addCriterion("company_contact_id_card =", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardNotEqualTo(String value) {
            addCriterion("company_contact_id_card <>", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardGreaterThan(String value) {
            addCriterion("company_contact_id_card >", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("company_contact_id_card >=", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardLessThan(String value) {
            addCriterion("company_contact_id_card <", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardLessThanOrEqualTo(String value) {
            addCriterion("company_contact_id_card <=", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardLike(String value) {
            addCriterion("company_contact_id_card like", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardNotLike(String value) {
            addCriterion("company_contact_id_card not like", value, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardIn(List<String> values) {
            addCriterion("company_contact_id_card in", values, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardNotIn(List<String> values) {
            addCriterion("company_contact_id_card not in", values, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardBetween(String value1, String value2) {
            addCriterion("company_contact_id_card between", value1, value2, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyContactIdCardNotBetween(String value1, String value2) {
            addCriterion("company_contact_id_card not between", value1, value2, "companyContactIdCard");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNull() {
            addCriterion("company_tel is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNotNull() {
            addCriterion("company_tel is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelEqualTo(String value) {
            addCriterion("company_tel =", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotEqualTo(String value) {
            addCriterion("company_tel <>", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThan(String value) {
            addCriterion("company_tel >", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThanOrEqualTo(String value) {
            addCriterion("company_tel >=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThan(String value) {
            addCriterion("company_tel <", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThanOrEqualTo(String value) {
            addCriterion("company_tel <=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLike(String value) {
            addCriterion("company_tel like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotLike(String value) {
            addCriterion("company_tel not like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIn(List<String> values) {
            addCriterion("company_tel in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotIn(List<String> values) {
            addCriterion("company_tel not in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelBetween(String value1, String value2) {
            addCriterion("company_tel between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotBetween(String value1, String value2) {
            addCriterion("company_tel not between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIsNull() {
            addCriterion("company_email is null");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIsNotNull() {
            addCriterion("company_email is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailEqualTo(String value) {
            addCriterion("company_email =", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotEqualTo(String value) {
            addCriterion("company_email <>", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailGreaterThan(String value) {
            addCriterion("company_email >", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailGreaterThanOrEqualTo(String value) {
            addCriterion("company_email >=", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLessThan(String value) {
            addCriterion("company_email <", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLessThanOrEqualTo(String value) {
            addCriterion("company_email <=", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailLike(String value) {
            addCriterion("company_email like", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotLike(String value) {
            addCriterion("company_email not like", value, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailIn(List<String> values) {
            addCriterion("company_email in", values, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotIn(List<String> values) {
            addCriterion("company_email not in", values, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailBetween(String value1, String value2) {
            addCriterion("company_email between", value1, value2, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyEmailNotBetween(String value1, String value2) {
            addCriterion("company_email not between", value1, value2, "companyEmail");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNull() {
            addCriterion("company_status is null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIsNotNull() {
            addCriterion("company_status is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusEqualTo(Integer value) {
            addCriterion("company_status =", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotEqualTo(Integer value) {
            addCriterion("company_status <>", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThan(Integer value) {
            addCriterion("company_status >", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_status >=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThan(Integer value) {
            addCriterion("company_status <", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusLessThanOrEqualTo(Integer value) {
            addCriterion("company_status <=", value, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusIn(List<Integer> values) {
            addCriterion("company_status in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotIn(List<Integer> values) {
            addCriterion("company_status not in", values, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusBetween(Integer value1, Integer value2) {
            addCriterion("company_status between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("company_status not between", value1, value2, "companyStatus");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeIsNull() {
            addCriterion("company_create_time is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeIsNotNull() {
            addCriterion("company_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeEqualTo(Date value) {
            addCriterion("company_create_time =", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeNotEqualTo(Date value) {
            addCriterion("company_create_time <>", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeGreaterThan(Date value) {
            addCriterion("company_create_time >", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("company_create_time >=", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeLessThan(Date value) {
            addCriterion("company_create_time <", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("company_create_time <=", value, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeIn(List<Date> values) {
            addCriterion("company_create_time in", values, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeNotIn(List<Date> values) {
            addCriterion("company_create_time not in", values, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeBetween(Date value1, Date value2) {
            addCriterion("company_create_time between", value1, value2, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("company_create_time not between", value1, value2, "companyCreateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdIsNull() {
            addCriterion("company_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdIsNotNull() {
            addCriterion("company_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdEqualTo(String value) {
            addCriterion("company_create_user_id =", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdNotEqualTo(String value) {
            addCriterion("company_create_user_id <>", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdGreaterThan(String value) {
            addCriterion("company_create_user_id >", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_create_user_id >=", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdLessThan(String value) {
            addCriterion("company_create_user_id <", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("company_create_user_id <=", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdLike(String value) {
            addCriterion("company_create_user_id like", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdNotLike(String value) {
            addCriterion("company_create_user_id not like", value, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdIn(List<String> values) {
            addCriterion("company_create_user_id in", values, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdNotIn(List<String> values) {
            addCriterion("company_create_user_id not in", values, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdBetween(String value1, String value2) {
            addCriterion("company_create_user_id between", value1, value2, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("company_create_user_id not between", value1, value2, "companyCreateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeIsNull() {
            addCriterion("company_update_time is null");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeIsNotNull() {
            addCriterion("company_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeEqualTo(Date value) {
            addCriterion("company_update_time =", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeNotEqualTo(Date value) {
            addCriterion("company_update_time <>", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeGreaterThan(Date value) {
            addCriterion("company_update_time >", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("company_update_time >=", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeLessThan(Date value) {
            addCriterion("company_update_time <", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("company_update_time <=", value, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeIn(List<Date> values) {
            addCriterion("company_update_time in", values, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeNotIn(List<Date> values) {
            addCriterion("company_update_time not in", values, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("company_update_time between", value1, value2, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("company_update_time not between", value1, value2, "companyUpdateTime");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdIsNull() {
            addCriterion("company_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdIsNotNull() {
            addCriterion("company_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdEqualTo(String value) {
            addCriterion("company_update_user_id =", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdNotEqualTo(String value) {
            addCriterion("company_update_user_id <>", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdGreaterThan(String value) {
            addCriterion("company_update_user_id >", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_update_user_id >=", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdLessThan(String value) {
            addCriterion("company_update_user_id <", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("company_update_user_id <=", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdLike(String value) {
            addCriterion("company_update_user_id like", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdNotLike(String value) {
            addCriterion("company_update_user_id not like", value, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdIn(List<String> values) {
            addCriterion("company_update_user_id in", values, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdNotIn(List<String> values) {
            addCriterion("company_update_user_id not in", values, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdBetween(String value1, String value2) {
            addCriterion("company_update_user_id between", value1, value2, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("company_update_user_id not between", value1, value2, "companyUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteIsNull() {
            addCriterion("company_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteIsNotNull() {
            addCriterion("company_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteEqualTo(Boolean value) {
            addCriterion("company_is_delete =", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteNotEqualTo(Boolean value) {
            addCriterion("company_is_delete <>", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteGreaterThan(Boolean value) {
            addCriterion("company_is_delete >", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("company_is_delete >=", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteLessThan(Boolean value) {
            addCriterion("company_is_delete <", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("company_is_delete <=", value, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteIn(List<Boolean> values) {
            addCriterion("company_is_delete in", values, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteNotIn(List<Boolean> values) {
            addCriterion("company_is_delete not in", values, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("company_is_delete between", value1, value2, "companyIsDelete");
            return (Criteria) this;
        }

        public Criteria andCompanyIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("company_is_delete not between", value1, value2, "companyIsDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   company
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   company
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}