package com.test.manage.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NoticeExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sys_notice
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sys_notice
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sys_notice
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public NoticeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   sys_notice
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysNoticeIdIsNull() {
            addCriterion("sys_notice_id is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdIsNotNull() {
            addCriterion("sys_notice_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdEqualTo(String value) {
            addCriterion("sys_notice_id =", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdNotEqualTo(String value) {
            addCriterion("sys_notice_id <>", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdGreaterThan(String value) {
            addCriterion("sys_notice_id >", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_notice_id >=", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdLessThan(String value) {
            addCriterion("sys_notice_id <", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdLessThanOrEqualTo(String value) {
            addCriterion("sys_notice_id <=", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdLike(String value) {
            addCriterion("sys_notice_id like", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdNotLike(String value) {
            addCriterion("sys_notice_id not like", value, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdIn(List<String> values) {
            addCriterion("sys_notice_id in", values, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdNotIn(List<String> values) {
            addCriterion("sys_notice_id not in", values, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdBetween(String value1, String value2) {
            addCriterion("sys_notice_id between", value1, value2, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIdNotBetween(String value1, String value2) {
            addCriterion("sys_notice_id not between", value1, value2, "sysNoticeId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleIsNull() {
            addCriterion("sys_notice_title is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleIsNotNull() {
            addCriterion("sys_notice_title is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleEqualTo(String value) {
            addCriterion("sys_notice_title =", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleNotEqualTo(String value) {
            addCriterion("sys_notice_title <>", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleGreaterThan(String value) {
            addCriterion("sys_notice_title >", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleGreaterThanOrEqualTo(String value) {
            addCriterion("sys_notice_title >=", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleLessThan(String value) {
            addCriterion("sys_notice_title <", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleLessThanOrEqualTo(String value) {
            addCriterion("sys_notice_title <=", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleLike(String value) {
            addCriterion("sys_notice_title like", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleNotLike(String value) {
            addCriterion("sys_notice_title not like", value, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleIn(List<String> values) {
            addCriterion("sys_notice_title in", values, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleNotIn(List<String> values) {
            addCriterion("sys_notice_title not in", values, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleBetween(String value1, String value2) {
            addCriterion("sys_notice_title between", value1, value2, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeTitleNotBetween(String value1, String value2) {
            addCriterion("sys_notice_title not between", value1, value2, "sysNoticeTitle");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentIsNull() {
            addCriterion("sys_notice_content is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentIsNotNull() {
            addCriterion("sys_notice_content is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentEqualTo(String value) {
            addCriterion("sys_notice_content =", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentNotEqualTo(String value) {
            addCriterion("sys_notice_content <>", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentGreaterThan(String value) {
            addCriterion("sys_notice_content >", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentGreaterThanOrEqualTo(String value) {
            addCriterion("sys_notice_content >=", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentLessThan(String value) {
            addCriterion("sys_notice_content <", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentLessThanOrEqualTo(String value) {
            addCriterion("sys_notice_content <=", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentLike(String value) {
            addCriterion("sys_notice_content like", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentNotLike(String value) {
            addCriterion("sys_notice_content not like", value, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentIn(List<String> values) {
            addCriterion("sys_notice_content in", values, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentNotIn(List<String> values) {
            addCriterion("sys_notice_content not in", values, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentBetween(String value1, String value2) {
            addCriterion("sys_notice_content between", value1, value2, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeContentNotBetween(String value1, String value2) {
            addCriterion("sys_notice_content not between", value1, value2, "sysNoticeContent");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeIsNull() {
            addCriterion("sys_notice_issue_time is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeIsNotNull() {
            addCriterion("sys_notice_issue_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeEqualTo(Date value) {
            addCriterion("sys_notice_issue_time =", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeNotEqualTo(Date value) {
            addCriterion("sys_notice_issue_time <>", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeGreaterThan(Date value) {
            addCriterion("sys_notice_issue_time >", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_notice_issue_time >=", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeLessThan(Date value) {
            addCriterion("sys_notice_issue_time <", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_notice_issue_time <=", value, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeIn(List<Date> values) {
            addCriterion("sys_notice_issue_time in", values, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeNotIn(List<Date> values) {
            addCriterion("sys_notice_issue_time not in", values, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeBetween(Date value1, Date value2) {
            addCriterion("sys_notice_issue_time between", value1, value2, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIssueTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_notice_issue_time not between", value1, value2, "sysNoticeIssueTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeIsNull() {
            addCriterion("sys_notice_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeIsNotNull() {
            addCriterion("sys_notice_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeEqualTo(Date value) {
            addCriterion("sys_notice_end_time =", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeNotEqualTo(Date value) {
            addCriterion("sys_notice_end_time <>", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeGreaterThan(Date value) {
            addCriterion("sys_notice_end_time >", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_notice_end_time >=", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeLessThan(Date value) {
            addCriterion("sys_notice_end_time <", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_notice_end_time <=", value, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeIn(List<Date> values) {
            addCriterion("sys_notice_end_time in", values, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeNotIn(List<Date> values) {
            addCriterion("sys_notice_end_time not in", values, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeBetween(Date value1, Date value2) {
            addCriterion("sys_notice_end_time between", value1, value2, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_notice_end_time not between", value1, value2, "sysNoticeEndTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdIsNull() {
            addCriterion("sys_notice_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdIsNotNull() {
            addCriterion("sys_notice_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdEqualTo(String value) {
            addCriterion("sys_notice_create_user_id =", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdNotEqualTo(String value) {
            addCriterion("sys_notice_create_user_id <>", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdGreaterThan(String value) {
            addCriterion("sys_notice_create_user_id >", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_notice_create_user_id >=", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdLessThan(String value) {
            addCriterion("sys_notice_create_user_id <", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("sys_notice_create_user_id <=", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdLike(String value) {
            addCriterion("sys_notice_create_user_id like", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdNotLike(String value) {
            addCriterion("sys_notice_create_user_id not like", value, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdIn(List<String> values) {
            addCriterion("sys_notice_create_user_id in", values, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdNotIn(List<String> values) {
            addCriterion("sys_notice_create_user_id not in", values, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdBetween(String value1, String value2) {
            addCriterion("sys_notice_create_user_id between", value1, value2, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("sys_notice_create_user_id not between", value1, value2, "sysNoticeCreateUserId");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeIsNull() {
            addCriterion("sys_notice_create_time is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeIsNotNull() {
            addCriterion("sys_notice_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeEqualTo(Date value) {
            addCriterion("sys_notice_create_time =", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeNotEqualTo(Date value) {
            addCriterion("sys_notice_create_time <>", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeGreaterThan(Date value) {
            addCriterion("sys_notice_create_time >", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sys_notice_create_time >=", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeLessThan(Date value) {
            addCriterion("sys_notice_create_time <", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("sys_notice_create_time <=", value, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeIn(List<Date> values) {
            addCriterion("sys_notice_create_time in", values, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeNotIn(List<Date> values) {
            addCriterion("sys_notice_create_time not in", values, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeBetween(Date value1, Date value2) {
            addCriterion("sys_notice_create_time between", value1, value2, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("sys_notice_create_time not between", value1, value2, "sysNoticeCreateTime");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteIsNull() {
            addCriterion("sys_notice_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteIsNotNull() {
            addCriterion("sys_notice_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteEqualTo(Boolean value) {
            addCriterion("sys_notice_is_delete =", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteNotEqualTo(Boolean value) {
            addCriterion("sys_notice_is_delete <>", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteGreaterThan(Boolean value) {
            addCriterion("sys_notice_is_delete >", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sys_notice_is_delete >=", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteLessThan(Boolean value) {
            addCriterion("sys_notice_is_delete <", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("sys_notice_is_delete <=", value, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteIn(List<Boolean> values) {
            addCriterion("sys_notice_is_delete in", values, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteNotIn(List<Boolean> values) {
            addCriterion("sys_notice_is_delete not in", values, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_notice_is_delete between", value1, value2, "sysNoticeIsDelete");
            return (Criteria) this;
        }

        public Criteria andSysNoticeIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sys_notice_is_delete not between", value1, value2, "sysNoticeIsDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   sys_notice
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   sys_notice
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}