druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIPiwqOnHu7WXwD/cN/qJM57VtzuATzjhbYiLh+TgK+t3xXgsGBMA9j/cgvz9WSh+5TwoxDJRwDcO/qIg8v9e7sCAwEAAQ==

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.131.32:3306/dleb?verifyServerCertificate=false&useSSL=false
      username: root
      password: PCfPmNhSE1Qtb5nhVXmHU8iYkBpnb6WJnCFlaU2inoYj2F8zR+AC092bFuRYwpBsRuWX5yiTUR75mzMgTRlvdw==
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
      database: 1
      host: 172.20.131.32
      port: 6389
      password: zuDz9mGGqkAbApEUWAy6
      timeout: 3000
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
awesome:
  jwt:
    issuer: awesomeApp
    base64EncodedSecretKey: awesomeSecretKey
  ebpay:
    uid: K78076
    mrchCode: 3284
    masterId: 2000863670
    smsAccount: dllg,1538
    smsPwd: dllgadmin
    smsSignature: 【德邻陆港】
    staticUrl: http://epaystatic.dllg56.com
    staticPath: /app/static
    projectPath: ebpay
    fundSummaryAcctNo: 15000092082259
    tradeCallbackUrl: http://epayapi.dllg56.com/callback/pa/trade/inspection
    setPasswordBackUrl: http://epayapi.dllg56.com/accountSub/accountSubController/returnBack
    businessCallBackUrl: http://epayapi.dllg56.com/api/pay/paymentCallBack
    transferReturnUrl: http://epay.dllg56.com/FrontHome
    paymentDisposeReturnUrl: http://epay.dllg56.com/Payment
    frontUrl: https://ebank.sdb.com.cn/corporbank/nonpartyVerify.do
    topupUrl: https://ebank.sdb.com.cn/khpayment/khPayment_sfj.do
    returnbackForBusiness: http://epayapi.dllg56.com/pay/returnbackForBusiness
    returnback: http://epayapi.dllg56.com/pay/returnback
    reimburseBackUrl: http://epayapi.dllg56.com/refund/reimburseBack