package com.dllg.ebpay.dao.generator;

import com.dllg.ebpay.model.generator.SuperInternetBank;
import com.dllg.ebpay.model.generator.SuperInternetBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuperInternetBankMapper {
    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    long countByExample(SuperInternetBankExample example);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    int deleteByExample(SuperInternetBankExample example);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    int insert(SuperInternetBank record);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    int insertSelective(SuperInternetBank record);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    List<SuperInternetBank> selectByExample(SuperInternetBankExample example);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SuperInternetBank record, @Param("example") SuperInternetBankExample example);

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    int updateByExample(@Param("record") SuperInternetBank record, @Param("example") SuperInternetBankExample example);
}