package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BankCardExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table bank_card
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table bank_card
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table bank_card
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public BankCardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   bank_card
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankCardIdIsNull() {
            addCriterion("bank_card_id is null");
            return (Criteria) this;
        }

        public Criteria andBankCardIdIsNotNull() {
            addCriterion("bank_card_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardIdEqualTo(String value) {
            addCriterion("bank_card_id =", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdNotEqualTo(String value) {
            addCriterion("bank_card_id <>", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdGreaterThan(String value) {
            addCriterion("bank_card_id >", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_id >=", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdLessThan(String value) {
            addCriterion("bank_card_id <", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdLessThanOrEqualTo(String value) {
            addCriterion("bank_card_id <=", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdLike(String value) {
            addCriterion("bank_card_id like", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdNotLike(String value) {
            addCriterion("bank_card_id not like", value, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdIn(List<String> values) {
            addCriterion("bank_card_id in", values, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdNotIn(List<String> values) {
            addCriterion("bank_card_id not in", values, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdBetween(String value1, String value2) {
            addCriterion("bank_card_id between", value1, value2, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardIdNotBetween(String value1, String value2) {
            addCriterion("bank_card_id not between", value1, value2, "bankCardId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdIsNull() {
            addCriterion("bank_card_account_sub_id is null");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdIsNotNull() {
            addCriterion("bank_card_account_sub_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdEqualTo(String value) {
            addCriterion("bank_card_account_sub_id =", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdNotEqualTo(String value) {
            addCriterion("bank_card_account_sub_id <>", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdGreaterThan(String value) {
            addCriterion("bank_card_account_sub_id >", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_account_sub_id >=", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdLessThan(String value) {
            addCriterion("bank_card_account_sub_id <", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdLessThanOrEqualTo(String value) {
            addCriterion("bank_card_account_sub_id <=", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdLike(String value) {
            addCriterion("bank_card_account_sub_id like", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdNotLike(String value) {
            addCriterion("bank_card_account_sub_id not like", value, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdIn(List<String> values) {
            addCriterion("bank_card_account_sub_id in", values, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdNotIn(List<String> values) {
            addCriterion("bank_card_account_sub_id not in", values, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdBetween(String value1, String value2) {
            addCriterion("bank_card_account_sub_id between", value1, value2, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardAccountSubIdNotBetween(String value1, String value2) {
            addCriterion("bank_card_account_sub_id not between", value1, value2, "bankCardAccountSubId");
            return (Criteria) this;
        }

        public Criteria andBankCardBankIsNull() {
            addCriterion("bank_card_bank is null");
            return (Criteria) this;
        }

        public Criteria andBankCardBankIsNotNull() {
            addCriterion("bank_card_bank is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardBankEqualTo(String value) {
            addCriterion("bank_card_bank =", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankNotEqualTo(String value) {
            addCriterion("bank_card_bank <>", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankGreaterThan(String value) {
            addCriterion("bank_card_bank >", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_bank >=", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankLessThan(String value) {
            addCriterion("bank_card_bank <", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankLessThanOrEqualTo(String value) {
            addCriterion("bank_card_bank <=", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankLike(String value) {
            addCriterion("bank_card_bank like", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankNotLike(String value) {
            addCriterion("bank_card_bank not like", value, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankIn(List<String> values) {
            addCriterion("bank_card_bank in", values, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankNotIn(List<String> values) {
            addCriterion("bank_card_bank not in", values, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBetween(String value1, String value2) {
            addCriterion("bank_card_bank between", value1, value2, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankNotBetween(String value1, String value2) {
            addCriterion("bank_card_bank not between", value1, value2, "bankCardBank");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchIsNull() {
            addCriterion("bank_card_bank_branch is null");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchIsNotNull() {
            addCriterion("bank_card_bank_branch is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchEqualTo(String value) {
            addCriterion("bank_card_bank_branch =", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchNotEqualTo(String value) {
            addCriterion("bank_card_bank_branch <>", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchGreaterThan(String value) {
            addCriterion("bank_card_bank_branch >", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_bank_branch >=", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchLessThan(String value) {
            addCriterion("bank_card_bank_branch <", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchLessThanOrEqualTo(String value) {
            addCriterion("bank_card_bank_branch <=", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchLike(String value) {
            addCriterion("bank_card_bank_branch like", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchNotLike(String value) {
            addCriterion("bank_card_bank_branch not like", value, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchIn(List<String> values) {
            addCriterion("bank_card_bank_branch in", values, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchNotIn(List<String> values) {
            addCriterion("bank_card_bank_branch not in", values, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchBetween(String value1, String value2) {
            addCriterion("bank_card_bank_branch between", value1, value2, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardBankBranchNotBetween(String value1, String value2) {
            addCriterion("bank_card_bank_branch not between", value1, value2, "bankCardBankBranch");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeIsNull() {
            addCriterion("bank_card_type is null");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeIsNotNull() {
            addCriterion("bank_card_type is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeEqualTo(String value) {
            addCriterion("bank_card_type =", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeNotEqualTo(String value) {
            addCriterion("bank_card_type <>", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeGreaterThan(String value) {
            addCriterion("bank_card_type >", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_type >=", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeLessThan(String value) {
            addCriterion("bank_card_type <", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeLessThanOrEqualTo(String value) {
            addCriterion("bank_card_type <=", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeLike(String value) {
            addCriterion("bank_card_type like", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeNotLike(String value) {
            addCriterion("bank_card_type not like", value, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeIn(List<String> values) {
            addCriterion("bank_card_type in", values, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeNotIn(List<String> values) {
            addCriterion("bank_card_type not in", values, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeBetween(String value1, String value2) {
            addCriterion("bank_card_type between", value1, value2, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardTypeNotBetween(String value1, String value2) {
            addCriterion("bank_card_type not between", value1, value2, "bankCardType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeIsNull() {
            addCriterion("bank_card_master_type is null");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeIsNotNull() {
            addCriterion("bank_card_master_type is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeEqualTo(Integer value) {
            addCriterion("bank_card_master_type =", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeNotEqualTo(Integer value) {
            addCriterion("bank_card_master_type <>", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeGreaterThan(Integer value) {
            addCriterion("bank_card_master_type >", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bank_card_master_type >=", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeLessThan(Integer value) {
            addCriterion("bank_card_master_type <", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeLessThanOrEqualTo(Integer value) {
            addCriterion("bank_card_master_type <=", value, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeIn(List<Integer> values) {
            addCriterion("bank_card_master_type in", values, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeNotIn(List<Integer> values) {
            addCriterion("bank_card_master_type not in", values, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_master_type between", value1, value2, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardMasterTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_master_type not between", value1, value2, "bankCardMasterType");
            return (Criteria) this;
        }

        public Criteria andBankCardNoIsNull() {
            addCriterion("bank_card_no is null");
            return (Criteria) this;
        }

        public Criteria andBankCardNoIsNotNull() {
            addCriterion("bank_card_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardNoEqualTo(String value) {
            addCriterion("bank_card_no =", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoNotEqualTo(String value) {
            addCriterion("bank_card_no <>", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoGreaterThan(String value) {
            addCriterion("bank_card_no >", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_no >=", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoLessThan(String value) {
            addCriterion("bank_card_no <", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoLessThanOrEqualTo(String value) {
            addCriterion("bank_card_no <=", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoLike(String value) {
            addCriterion("bank_card_no like", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoNotLike(String value) {
            addCriterion("bank_card_no not like", value, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoIn(List<String> values) {
            addCriterion("bank_card_no in", values, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoNotIn(List<String> values) {
            addCriterion("bank_card_no not in", values, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoBetween(String value1, String value2) {
            addCriterion("bank_card_no between", value1, value2, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardNoNotBetween(String value1, String value2) {
            addCriterion("bank_card_no not between", value1, value2, "bankCardNo");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameIsNull() {
            addCriterion("bank_card_reserve_bank_account_name is null");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameIsNotNull() {
            addCriterion("bank_card_reserve_bank_account_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameEqualTo(String value) {
            addCriterion("bank_card_reserve_bank_account_name =", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameNotEqualTo(String value) {
            addCriterion("bank_card_reserve_bank_account_name <>", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameGreaterThan(String value) {
            addCriterion("bank_card_reserve_bank_account_name >", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_reserve_bank_account_name >=", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameLessThan(String value) {
            addCriterion("bank_card_reserve_bank_account_name <", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameLessThanOrEqualTo(String value) {
            addCriterion("bank_card_reserve_bank_account_name <=", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameLike(String value) {
            addCriterion("bank_card_reserve_bank_account_name like", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameNotLike(String value) {
            addCriterion("bank_card_reserve_bank_account_name not like", value, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameIn(List<String> values) {
            addCriterion("bank_card_reserve_bank_account_name in", values, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameNotIn(List<String> values) {
            addCriterion("bank_card_reserve_bank_account_name not in", values, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameBetween(String value1, String value2) {
            addCriterion("bank_card_reserve_bank_account_name between", value1, value2, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveBankAccountNameNotBetween(String value1, String value2) {
            addCriterion("bank_card_reserve_bank_account_name not between", value1, value2, "bankCardReserveBankAccountName");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileIsNull() {
            addCriterion("bank_card_reserve_mobile is null");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileIsNotNull() {
            addCriterion("bank_card_reserve_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileEqualTo(String value) {
            addCriterion("bank_card_reserve_mobile =", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileNotEqualTo(String value) {
            addCriterion("bank_card_reserve_mobile <>", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileGreaterThan(String value) {
            addCriterion("bank_card_reserve_mobile >", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_reserve_mobile >=", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileLessThan(String value) {
            addCriterion("bank_card_reserve_mobile <", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileLessThanOrEqualTo(String value) {
            addCriterion("bank_card_reserve_mobile <=", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileLike(String value) {
            addCriterion("bank_card_reserve_mobile like", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileNotLike(String value) {
            addCriterion("bank_card_reserve_mobile not like", value, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileIn(List<String> values) {
            addCriterion("bank_card_reserve_mobile in", values, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileNotIn(List<String> values) {
            addCriterion("bank_card_reserve_mobile not in", values, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileBetween(String value1, String value2) {
            addCriterion("bank_card_reserve_mobile between", value1, value2, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardReserveMobileNotBetween(String value1, String value2) {
            addCriterion("bank_card_reserve_mobile not between", value1, value2, "bankCardReserveMobile");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeIsNull() {
            addCriterion("bank_card_document_type is null");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeIsNotNull() {
            addCriterion("bank_card_document_type is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeEqualTo(String value) {
            addCriterion("bank_card_document_type =", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeNotEqualTo(String value) {
            addCriterion("bank_card_document_type <>", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeGreaterThan(String value) {
            addCriterion("bank_card_document_type >", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_document_type >=", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeLessThan(String value) {
            addCriterion("bank_card_document_type <", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeLessThanOrEqualTo(String value) {
            addCriterion("bank_card_document_type <=", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeLike(String value) {
            addCriterion("bank_card_document_type like", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeNotLike(String value) {
            addCriterion("bank_card_document_type not like", value, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeIn(List<String> values) {
            addCriterion("bank_card_document_type in", values, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeNotIn(List<String> values) {
            addCriterion("bank_card_document_type not in", values, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeBetween(String value1, String value2) {
            addCriterion("bank_card_document_type between", value1, value2, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentTypeNotBetween(String value1, String value2) {
            addCriterion("bank_card_document_type not between", value1, value2, "bankCardDocumentType");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoIsNull() {
            addCriterion("bank_card_document_no is null");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoIsNotNull() {
            addCriterion("bank_card_document_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoEqualTo(String value) {
            addCriterion("bank_card_document_no =", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoNotEqualTo(String value) {
            addCriterion("bank_card_document_no <>", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoGreaterThan(String value) {
            addCriterion("bank_card_document_no >", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_document_no >=", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoLessThan(String value) {
            addCriterion("bank_card_document_no <", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoLessThanOrEqualTo(String value) {
            addCriterion("bank_card_document_no <=", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoLike(String value) {
            addCriterion("bank_card_document_no like", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoNotLike(String value) {
            addCriterion("bank_card_document_no not like", value, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoIn(List<String> values) {
            addCriterion("bank_card_document_no in", values, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoNotIn(List<String> values) {
            addCriterion("bank_card_document_no not in", values, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoBetween(String value1, String value2) {
            addCriterion("bank_card_document_no between", value1, value2, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardDocumentNoNotBetween(String value1, String value2) {
            addCriterion("bank_card_document_no not between", value1, value2, "bankCardDocumentNo");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeIsNull() {
            addCriterion("bank_card_transaction_amount_type is null");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeIsNotNull() {
            addCriterion("bank_card_transaction_amount_type is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeEqualTo(Integer value) {
            addCriterion("bank_card_transaction_amount_type =", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeNotEqualTo(Integer value) {
            addCriterion("bank_card_transaction_amount_type <>", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeGreaterThan(Integer value) {
            addCriterion("bank_card_transaction_amount_type >", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("bank_card_transaction_amount_type >=", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeLessThan(Integer value) {
            addCriterion("bank_card_transaction_amount_type <", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeLessThanOrEqualTo(Integer value) {
            addCriterion("bank_card_transaction_amount_type <=", value, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeIn(List<Integer> values) {
            addCriterion("bank_card_transaction_amount_type in", values, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeNotIn(List<Integer> values) {
            addCriterion("bank_card_transaction_amount_type not in", values, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_transaction_amount_type between", value1, value2, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardTransactionAmountTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_transaction_amount_type not between", value1, value2, "bankCardTransactionAmountType");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusIsNull() {
            addCriterion("bank_card_status is null");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusIsNotNull() {
            addCriterion("bank_card_status is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusEqualTo(Integer value) {
            addCriterion("bank_card_status =", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusNotEqualTo(Integer value) {
            addCriterion("bank_card_status <>", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusGreaterThan(Integer value) {
            addCriterion("bank_card_status >", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("bank_card_status >=", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusLessThan(Integer value) {
            addCriterion("bank_card_status <", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusLessThanOrEqualTo(Integer value) {
            addCriterion("bank_card_status <=", value, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusIn(List<Integer> values) {
            addCriterion("bank_card_status in", values, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusNotIn(List<Integer> values) {
            addCriterion("bank_card_status not in", values, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_status between", value1, value2, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("bank_card_status not between", value1, value2, "bankCardStatus");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateIsNull() {
            addCriterion("bank_card_bind_bank_card_date is null");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateIsNotNull() {
            addCriterion("bank_card_bind_bank_card_date is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateEqualTo(Date value) {
            addCriterion("bank_card_bind_bank_card_date =", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateNotEqualTo(Date value) {
            addCriterion("bank_card_bind_bank_card_date <>", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateGreaterThan(Date value) {
            addCriterion("bank_card_bind_bank_card_date >", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateGreaterThanOrEqualTo(Date value) {
            addCriterion("bank_card_bind_bank_card_date >=", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateLessThan(Date value) {
            addCriterion("bank_card_bind_bank_card_date <", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateLessThanOrEqualTo(Date value) {
            addCriterion("bank_card_bind_bank_card_date <=", value, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateIn(List<Date> values) {
            addCriterion("bank_card_bind_bank_card_date in", values, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateNotIn(List<Date> values) {
            addCriterion("bank_card_bind_bank_card_date not in", values, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateBetween(Date value1, Date value2) {
            addCriterion("bank_card_bind_bank_card_date between", value1, value2, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardBindBankCardDateNotBetween(Date value1, Date value2) {
            addCriterion("bank_card_bind_bank_card_date not between", value1, value2, "bankCardBindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateIsNull() {
            addCriterion("bank_card_unbind_bank_card_date is null");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateIsNotNull() {
            addCriterion("bank_card_unbind_bank_card_date is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateEqualTo(Date value) {
            addCriterion("bank_card_unbind_bank_card_date =", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateNotEqualTo(Date value) {
            addCriterion("bank_card_unbind_bank_card_date <>", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateGreaterThan(Date value) {
            addCriterion("bank_card_unbind_bank_card_date >", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateGreaterThanOrEqualTo(Date value) {
            addCriterion("bank_card_unbind_bank_card_date >=", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateLessThan(Date value) {
            addCriterion("bank_card_unbind_bank_card_date <", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateLessThanOrEqualTo(Date value) {
            addCriterion("bank_card_unbind_bank_card_date <=", value, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateIn(List<Date> values) {
            addCriterion("bank_card_unbind_bank_card_date in", values, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateNotIn(List<Date> values) {
            addCriterion("bank_card_unbind_bank_card_date not in", values, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateBetween(Date value1, Date value2) {
            addCriterion("bank_card_unbind_bank_card_date between", value1, value2, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardUnbindBankCardDateNotBetween(Date value1, Date value2) {
            addCriterion("bank_card_unbind_bank_card_date not between", value1, value2, "bankCardUnbindBankCardDate");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdIsNull() {
            addCriterion("bank_card_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdIsNotNull() {
            addCriterion("bank_card_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdEqualTo(String value) {
            addCriterion("bank_card_create_user_id =", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdNotEqualTo(String value) {
            addCriterion("bank_card_create_user_id <>", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdGreaterThan(String value) {
            addCriterion("bank_card_create_user_id >", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_create_user_id >=", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdLessThan(String value) {
            addCriterion("bank_card_create_user_id <", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("bank_card_create_user_id <=", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdLike(String value) {
            addCriterion("bank_card_create_user_id like", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdNotLike(String value) {
            addCriterion("bank_card_create_user_id not like", value, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdIn(List<String> values) {
            addCriterion("bank_card_create_user_id in", values, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdNotIn(List<String> values) {
            addCriterion("bank_card_create_user_id not in", values, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdBetween(String value1, String value2) {
            addCriterion("bank_card_create_user_id between", value1, value2, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("bank_card_create_user_id not between", value1, value2, "bankCardCreateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeIsNull() {
            addCriterion("bank_card_create_time is null");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeIsNotNull() {
            addCriterion("bank_card_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeEqualTo(Date value) {
            addCriterion("bank_card_create_time =", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeNotEqualTo(Date value) {
            addCriterion("bank_card_create_time <>", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeGreaterThan(Date value) {
            addCriterion("bank_card_create_time >", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bank_card_create_time >=", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeLessThan(Date value) {
            addCriterion("bank_card_create_time <", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("bank_card_create_time <=", value, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeIn(List<Date> values) {
            addCriterion("bank_card_create_time in", values, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeNotIn(List<Date> values) {
            addCriterion("bank_card_create_time not in", values, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeBetween(Date value1, Date value2) {
            addCriterion("bank_card_create_time between", value1, value2, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("bank_card_create_time not between", value1, value2, "bankCardCreateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdIsNull() {
            addCriterion("bank_card_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdIsNotNull() {
            addCriterion("bank_card_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdEqualTo(String value) {
            addCriterion("bank_card_update_user_id =", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdNotEqualTo(String value) {
            addCriterion("bank_card_update_user_id <>", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdGreaterThan(String value) {
            addCriterion("bank_card_update_user_id >", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card_update_user_id >=", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdLessThan(String value) {
            addCriterion("bank_card_update_user_id <", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("bank_card_update_user_id <=", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdLike(String value) {
            addCriterion("bank_card_update_user_id like", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdNotLike(String value) {
            addCriterion("bank_card_update_user_id not like", value, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdIn(List<String> values) {
            addCriterion("bank_card_update_user_id in", values, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdNotIn(List<String> values) {
            addCriterion("bank_card_update_user_id not in", values, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdBetween(String value1, String value2) {
            addCriterion("bank_card_update_user_id between", value1, value2, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("bank_card_update_user_id not between", value1, value2, "bankCardUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeIsNull() {
            addCriterion("bank_card_update_time is null");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeIsNotNull() {
            addCriterion("bank_card_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeEqualTo(Date value) {
            addCriterion("bank_card_update_time =", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeNotEqualTo(Date value) {
            addCriterion("bank_card_update_time <>", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeGreaterThan(Date value) {
            addCriterion("bank_card_update_time >", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("bank_card_update_time >=", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeLessThan(Date value) {
            addCriterion("bank_card_update_time <", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("bank_card_update_time <=", value, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeIn(List<Date> values) {
            addCriterion("bank_card_update_time in", values, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeNotIn(List<Date> values) {
            addCriterion("bank_card_update_time not in", values, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("bank_card_update_time between", value1, value2, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("bank_card_update_time not between", value1, value2, "bankCardUpdateTime");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteIsNull() {
            addCriterion("bank_card_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteIsNotNull() {
            addCriterion("bank_card_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteEqualTo(Boolean value) {
            addCriterion("bank_card_is_delete =", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteNotEqualTo(Boolean value) {
            addCriterion("bank_card_is_delete <>", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteGreaterThan(Boolean value) {
            addCriterion("bank_card_is_delete >", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("bank_card_is_delete >=", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteLessThan(Boolean value) {
            addCriterion("bank_card_is_delete <", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("bank_card_is_delete <=", value, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteIn(List<Boolean> values) {
            addCriterion("bank_card_is_delete in", values, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteNotIn(List<Boolean> values) {
            addCriterion("bank_card_is_delete not in", values, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("bank_card_is_delete between", value1, value2, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankCardIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("bank_card_is_delete not between", value1, value2, "bankCardIsDelete");
            return (Criteria) this;
        }

        public Criteria andBankLogoIsNull() {
            addCriterion("bank_logo is null");
            return (Criteria) this;
        }

        public Criteria andBankLogoIsNotNull() {
            addCriterion("bank_logo is not null");
            return (Criteria) this;
        }

        public Criteria andBankLogoEqualTo(String value) {
            addCriterion("bank_logo =", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotEqualTo(String value) {
            addCriterion("bank_logo <>", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoGreaterThan(String value) {
            addCriterion("bank_logo >", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_logo >=", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLessThan(String value) {
            addCriterion("bank_logo <", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLessThanOrEqualTo(String value) {
            addCriterion("bank_logo <=", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoLike(String value) {
            addCriterion("bank_logo like", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotLike(String value) {
            addCriterion("bank_logo not like", value, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoIn(List<String> values) {
            addCriterion("bank_logo in", values, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotIn(List<String> values) {
            addCriterion("bank_logo not in", values, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoBetween(String value1, String value2) {
            addCriterion("bank_logo between", value1, value2, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankLogoNotBetween(String value1, String value2) {
            addCriterion("bank_logo not between", value1, value2, "bankLogo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoIsNull() {
            addCriterion("bank_cnsmr_seq_no is null");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoIsNotNull() {
            addCriterion("bank_cnsmr_seq_no is not null");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoEqualTo(String value) {
            addCriterion("bank_cnsmr_seq_no =", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoNotEqualTo(String value) {
            addCriterion("bank_cnsmr_seq_no <>", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoGreaterThan(String value) {
            addCriterion("bank_cnsmr_seq_no >", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoGreaterThanOrEqualTo(String value) {
            addCriterion("bank_cnsmr_seq_no >=", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoLessThan(String value) {
            addCriterion("bank_cnsmr_seq_no <", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoLessThanOrEqualTo(String value) {
            addCriterion("bank_cnsmr_seq_no <=", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoLike(String value) {
            addCriterion("bank_cnsmr_seq_no like", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoNotLike(String value) {
            addCriterion("bank_cnsmr_seq_no not like", value, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoIn(List<String> values) {
            addCriterion("bank_cnsmr_seq_no in", values, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoNotIn(List<String> values) {
            addCriterion("bank_cnsmr_seq_no not in", values, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoBetween(String value1, String value2) {
            addCriterion("bank_cnsmr_seq_no between", value1, value2, "bankCnsmrSeqNo");
            return (Criteria) this;
        }

        public Criteria andBankCnsmrSeqNoNotBetween(String value1, String value2) {
            addCriterion("bank_cnsmr_seq_no not between", value1, value2, "bankCnsmrSeqNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   bank_card
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   bank_card
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}