package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JsonDataExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table json_data
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table json_data
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table json_data
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public JsonDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   json_data
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJsonDataIdIsNull() {
            addCriterion("json_data_id is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdIsNotNull() {
            addCriterion("json_data_id is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdEqualTo(String value) {
            addCriterion("json_data_id =", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdNotEqualTo(String value) {
            addCriterion("json_data_id <>", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdGreaterThan(String value) {
            addCriterion("json_data_id >", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdGreaterThanOrEqualTo(String value) {
            addCriterion("json_data_id >=", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdLessThan(String value) {
            addCriterion("json_data_id <", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdLessThanOrEqualTo(String value) {
            addCriterion("json_data_id <=", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdLike(String value) {
            addCriterion("json_data_id like", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdNotLike(String value) {
            addCriterion("json_data_id not like", value, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdIn(List<String> values) {
            addCriterion("json_data_id in", values, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdNotIn(List<String> values) {
            addCriterion("json_data_id not in", values, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdBetween(String value1, String value2) {
            addCriterion("json_data_id between", value1, value2, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataIdNotBetween(String value1, String value2) {
            addCriterion("json_data_id not between", value1, value2, "jsonDataId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdIsNull() {
            addCriterion("json_data_relation_id is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdIsNotNull() {
            addCriterion("json_data_relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdEqualTo(String value) {
            addCriterion("json_data_relation_id =", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdNotEqualTo(String value) {
            addCriterion("json_data_relation_id <>", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdGreaterThan(String value) {
            addCriterion("json_data_relation_id >", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("json_data_relation_id >=", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdLessThan(String value) {
            addCriterion("json_data_relation_id <", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdLessThanOrEqualTo(String value) {
            addCriterion("json_data_relation_id <=", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdLike(String value) {
            addCriterion("json_data_relation_id like", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdNotLike(String value) {
            addCriterion("json_data_relation_id not like", value, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdIn(List<String> values) {
            addCriterion("json_data_relation_id in", values, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdNotIn(List<String> values) {
            addCriterion("json_data_relation_id not in", values, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdBetween(String value1, String value2) {
            addCriterion("json_data_relation_id between", value1, value2, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataRelationIdNotBetween(String value1, String value2) {
            addCriterion("json_data_relation_id not between", value1, value2, "jsonDataRelationId");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameIsNull() {
            addCriterion("json_data_name is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameIsNotNull() {
            addCriterion("json_data_name is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameEqualTo(String value) {
            addCriterion("json_data_name =", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameNotEqualTo(String value) {
            addCriterion("json_data_name <>", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameGreaterThan(String value) {
            addCriterion("json_data_name >", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("json_data_name >=", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameLessThan(String value) {
            addCriterion("json_data_name <", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameLessThanOrEqualTo(String value) {
            addCriterion("json_data_name <=", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameLike(String value) {
            addCriterion("json_data_name like", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameNotLike(String value) {
            addCriterion("json_data_name not like", value, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameIn(List<String> values) {
            addCriterion("json_data_name in", values, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameNotIn(List<String> values) {
            addCriterion("json_data_name not in", values, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameBetween(String value1, String value2) {
            addCriterion("json_data_name between", value1, value2, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataNameNotBetween(String value1, String value2) {
            addCriterion("json_data_name not between", value1, value2, "jsonDataName");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestIsNull() {
            addCriterion("json_data_request is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestIsNotNull() {
            addCriterion("json_data_request is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestEqualTo(String value) {
            addCriterion("json_data_request =", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestNotEqualTo(String value) {
            addCriterion("json_data_request <>", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestGreaterThan(String value) {
            addCriterion("json_data_request >", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestGreaterThanOrEqualTo(String value) {
            addCriterion("json_data_request >=", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestLessThan(String value) {
            addCriterion("json_data_request <", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestLessThanOrEqualTo(String value) {
            addCriterion("json_data_request <=", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestLike(String value) {
            addCriterion("json_data_request like", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestNotLike(String value) {
            addCriterion("json_data_request not like", value, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestIn(List<String> values) {
            addCriterion("json_data_request in", values, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestNotIn(List<String> values) {
            addCriterion("json_data_request not in", values, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestBetween(String value1, String value2) {
            addCriterion("json_data_request between", value1, value2, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataRequestNotBetween(String value1, String value2) {
            addCriterion("json_data_request not between", value1, value2, "jsonDataRequest");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseIsNull() {
            addCriterion("json_data_response is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseIsNotNull() {
            addCriterion("json_data_response is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseEqualTo(String value) {
            addCriterion("json_data_response =", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseNotEqualTo(String value) {
            addCriterion("json_data_response <>", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseGreaterThan(String value) {
            addCriterion("json_data_response >", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseGreaterThanOrEqualTo(String value) {
            addCriterion("json_data_response >=", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseLessThan(String value) {
            addCriterion("json_data_response <", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseLessThanOrEqualTo(String value) {
            addCriterion("json_data_response <=", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseLike(String value) {
            addCriterion("json_data_response like", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseNotLike(String value) {
            addCriterion("json_data_response not like", value, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseIn(List<String> values) {
            addCriterion("json_data_response in", values, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseNotIn(List<String> values) {
            addCriterion("json_data_response not in", values, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseBetween(String value1, String value2) {
            addCriterion("json_data_response between", value1, value2, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataResponseNotBetween(String value1, String value2) {
            addCriterion("json_data_response not between", value1, value2, "jsonDataResponse");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeIsNull() {
            addCriterion("json_data_create_time is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeIsNotNull() {
            addCriterion("json_data_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeEqualTo(Date value) {
            addCriterion("json_data_create_time =", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeNotEqualTo(Date value) {
            addCriterion("json_data_create_time <>", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeGreaterThan(Date value) {
            addCriterion("json_data_create_time >", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("json_data_create_time >=", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeLessThan(Date value) {
            addCriterion("json_data_create_time <", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("json_data_create_time <=", value, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeIn(List<Date> values) {
            addCriterion("json_data_create_time in", values, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeNotIn(List<Date> values) {
            addCriterion("json_data_create_time not in", values, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeBetween(Date value1, Date value2) {
            addCriterion("json_data_create_time between", value1, value2, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("json_data_create_time not between", value1, value2, "jsonDataCreateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeIsNull() {
            addCriterion("json_data_update_time is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeIsNotNull() {
            addCriterion("json_data_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeEqualTo(Date value) {
            addCriterion("json_data_update_time =", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeNotEqualTo(Date value) {
            addCriterion("json_data_update_time <>", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeGreaterThan(Date value) {
            addCriterion("json_data_update_time >", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("json_data_update_time >=", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeLessThan(Date value) {
            addCriterion("json_data_update_time <", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("json_data_update_time <=", value, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeIn(List<Date> values) {
            addCriterion("json_data_update_time in", values, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeNotIn(List<Date> values) {
            addCriterion("json_data_update_time not in", values, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("json_data_update_time between", value1, value2, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("json_data_update_time not between", value1, value2, "jsonDataUpdateTime");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusIsNull() {
            addCriterion("json_data_status is null");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusIsNotNull() {
            addCriterion("json_data_status is not null");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusEqualTo(Integer value) {
            addCriterion("json_data_status =", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusNotEqualTo(Integer value) {
            addCriterion("json_data_status <>", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusGreaterThan(Integer value) {
            addCriterion("json_data_status >", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("json_data_status >=", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusLessThan(Integer value) {
            addCriterion("json_data_status <", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusLessThanOrEqualTo(Integer value) {
            addCriterion("json_data_status <=", value, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusIn(List<Integer> values) {
            addCriterion("json_data_status in", values, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusNotIn(List<Integer> values) {
            addCriterion("json_data_status not in", values, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusBetween(Integer value1, Integer value2) {
            addCriterion("json_data_status between", value1, value2, "jsonDataStatus");
            return (Criteria) this;
        }

        public Criteria andJsonDataStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("json_data_status not between", value1, value2, "jsonDataStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   json_data
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   json_data
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}