package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.List;

public class PubPayNodeExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table pub_pay_node
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table pub_pay_node
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table pub_pay_node
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public PubPayNodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   pub_pay_node
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNodeNodecodeIsNull() {
            addCriterion("node_nodecode is null");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeIsNotNull() {
            addCriterion("node_nodecode is not null");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeEqualTo(String value) {
            addCriterion("node_nodecode =", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeNotEqualTo(String value) {
            addCriterion("node_nodecode <>", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeGreaterThan(String value) {
            addCriterion("node_nodecode >", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeGreaterThanOrEqualTo(String value) {
            addCriterion("node_nodecode >=", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeLessThan(String value) {
            addCriterion("node_nodecode <", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeLessThanOrEqualTo(String value) {
            addCriterion("node_nodecode <=", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeLike(String value) {
            addCriterion("node_nodecode like", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeNotLike(String value) {
            addCriterion("node_nodecode not like", value, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeIn(List<String> values) {
            addCriterion("node_nodecode in", values, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeNotIn(List<String> values) {
            addCriterion("node_nodecode not in", values, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeBetween(String value1, String value2) {
            addCriterion("node_nodecode between", value1, value2, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodecodeNotBetween(String value1, String value2) {
            addCriterion("node_nodecode not between", value1, value2, "nodeNodecode");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameIsNull() {
            addCriterion("node_nodename is null");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameIsNotNull() {
            addCriterion("node_nodename is not null");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameEqualTo(String value) {
            addCriterion("node_nodename =", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameNotEqualTo(String value) {
            addCriterion("node_nodename <>", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameGreaterThan(String value) {
            addCriterion("node_nodename >", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameGreaterThanOrEqualTo(String value) {
            addCriterion("node_nodename >=", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameLessThan(String value) {
            addCriterion("node_nodename <", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameLessThanOrEqualTo(String value) {
            addCriterion("node_nodename <=", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameLike(String value) {
            addCriterion("node_nodename like", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameNotLike(String value) {
            addCriterion("node_nodename not like", value, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameIn(List<String> values) {
            addCriterion("node_nodename in", values, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameNotIn(List<String> values) {
            addCriterion("node_nodename not in", values, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameBetween(String value1, String value2) {
            addCriterion("node_nodename between", value1, value2, "nodeNodename");
            return (Criteria) this;
        }

        public Criteria andNodeNodenameNotBetween(String value1, String value2) {
            addCriterion("node_nodename not between", value1, value2, "nodeNodename");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   pub_pay_node
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   pub_pay_node
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}