package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourceExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table resource
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table resource
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table resource
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public ResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   resource
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResourceIdIsNull() {
            addCriterion("resource_id is null");
            return (Criteria) this;
        }

        public Criteria andResourceIdIsNotNull() {
            addCriterion("resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIdEqualTo(String value) {
            addCriterion("resource_id =", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotEqualTo(String value) {
            addCriterion("resource_id <>", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThan(String value) {
            addCriterion("resource_id >", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("resource_id >=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThan(String value) {
            addCriterion("resource_id <", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThanOrEqualTo(String value) {
            addCriterion("resource_id <=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLike(String value) {
            addCriterion("resource_id like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotLike(String value) {
            addCriterion("resource_id not like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdIn(List<String> values) {
            addCriterion("resource_id in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotIn(List<String> values) {
            addCriterion("resource_id not in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdBetween(String value1, String value2) {
            addCriterion("resource_id between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotBetween(String value1, String value2) {
            addCriterion("resource_id not between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdIsNull() {
            addCriterion("parent_resource_id is null");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdIsNotNull() {
            addCriterion("parent_resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdEqualTo(String value) {
            addCriterion("parent_resource_id =", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdNotEqualTo(String value) {
            addCriterion("parent_resource_id <>", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdGreaterThan(String value) {
            addCriterion("parent_resource_id >", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_resource_id >=", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdLessThan(String value) {
            addCriterion("parent_resource_id <", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdLessThanOrEqualTo(String value) {
            addCriterion("parent_resource_id <=", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdLike(String value) {
            addCriterion("parent_resource_id like", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdNotLike(String value) {
            addCriterion("parent_resource_id not like", value, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdIn(List<String> values) {
            addCriterion("parent_resource_id in", values, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdNotIn(List<String> values) {
            addCriterion("parent_resource_id not in", values, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdBetween(String value1, String value2) {
            addCriterion("parent_resource_id between", value1, value2, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andParentResourceIdNotBetween(String value1, String value2) {
            addCriterion("parent_resource_id not between", value1, value2, "parentResourceId");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNull() {
            addCriterion("resource_name is null");
            return (Criteria) this;
        }

        public Criteria andResourceNameIsNotNull() {
            addCriterion("resource_name is not null");
            return (Criteria) this;
        }

        public Criteria andResourceNameEqualTo(String value) {
            addCriterion("resource_name =", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotEqualTo(String value) {
            addCriterion("resource_name <>", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThan(String value) {
            addCriterion("resource_name >", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameGreaterThanOrEqualTo(String value) {
            addCriterion("resource_name >=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThan(String value) {
            addCriterion("resource_name <", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLessThanOrEqualTo(String value) {
            addCriterion("resource_name <=", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameLike(String value) {
            addCriterion("resource_name like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotLike(String value) {
            addCriterion("resource_name not like", value, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameIn(List<String> values) {
            addCriterion("resource_name in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotIn(List<String> values) {
            addCriterion("resource_name not in", values, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameBetween(String value1, String value2) {
            addCriterion("resource_name between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceNameNotBetween(String value1, String value2) {
            addCriterion("resource_name not between", value1, value2, "resourceName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameIsNull() {
            addCriterion("resource_en_name is null");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameIsNotNull() {
            addCriterion("resource_en_name is not null");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameEqualTo(String value) {
            addCriterion("resource_en_name =", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameNotEqualTo(String value) {
            addCriterion("resource_en_name <>", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameGreaterThan(String value) {
            addCriterion("resource_en_name >", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameGreaterThanOrEqualTo(String value) {
            addCriterion("resource_en_name >=", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameLessThan(String value) {
            addCriterion("resource_en_name <", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameLessThanOrEqualTo(String value) {
            addCriterion("resource_en_name <=", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameLike(String value) {
            addCriterion("resource_en_name like", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameNotLike(String value) {
            addCriterion("resource_en_name not like", value, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameIn(List<String> values) {
            addCriterion("resource_en_name in", values, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameNotIn(List<String> values) {
            addCriterion("resource_en_name not in", values, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameBetween(String value1, String value2) {
            addCriterion("resource_en_name between", value1, value2, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceEnNameNotBetween(String value1, String value2) {
            addCriterion("resource_en_name not between", value1, value2, "resourceEnName");
            return (Criteria) this;
        }

        public Criteria andResourceValueIsNull() {
            addCriterion("resource_value is null");
            return (Criteria) this;
        }

        public Criteria andResourceValueIsNotNull() {
            addCriterion("resource_value is not null");
            return (Criteria) this;
        }

        public Criteria andResourceValueEqualTo(String value) {
            addCriterion("resource_value =", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueNotEqualTo(String value) {
            addCriterion("resource_value <>", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueGreaterThan(String value) {
            addCriterion("resource_value >", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueGreaterThanOrEqualTo(String value) {
            addCriterion("resource_value >=", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueLessThan(String value) {
            addCriterion("resource_value <", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueLessThanOrEqualTo(String value) {
            addCriterion("resource_value <=", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueLike(String value) {
            addCriterion("resource_value like", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueNotLike(String value) {
            addCriterion("resource_value not like", value, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueIn(List<String> values) {
            addCriterion("resource_value in", values, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueNotIn(List<String> values) {
            addCriterion("resource_value not in", values, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueBetween(String value1, String value2) {
            addCriterion("resource_value between", value1, value2, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceValueNotBetween(String value1, String value2) {
            addCriterion("resource_value not between", value1, value2, "resourceValue");
            return (Criteria) this;
        }

        public Criteria andResourceIconIsNull() {
            addCriterion("resource_icon is null");
            return (Criteria) this;
        }

        public Criteria andResourceIconIsNotNull() {
            addCriterion("resource_icon is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIconEqualTo(String value) {
            addCriterion("resource_icon =", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconNotEqualTo(String value) {
            addCriterion("resource_icon <>", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconGreaterThan(String value) {
            addCriterion("resource_icon >", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconGreaterThanOrEqualTo(String value) {
            addCriterion("resource_icon >=", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconLessThan(String value) {
            addCriterion("resource_icon <", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconLessThanOrEqualTo(String value) {
            addCriterion("resource_icon <=", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconLike(String value) {
            addCriterion("resource_icon like", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconNotLike(String value) {
            addCriterion("resource_icon not like", value, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconIn(List<String> values) {
            addCriterion("resource_icon in", values, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconNotIn(List<String> values) {
            addCriterion("resource_icon not in", values, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconBetween(String value1, String value2) {
            addCriterion("resource_icon between", value1, value2, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceIconNotBetween(String value1, String value2) {
            addCriterion("resource_icon not between", value1, value2, "resourceIcon");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("resource_type is null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("resource_type is not null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeEqualTo(Integer value) {
            addCriterion("resource_type =", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotEqualTo(Integer value) {
            addCriterion("resource_type <>", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThan(Integer value) {
            addCriterion("resource_type >", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("resource_type >=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThan(Integer value) {
            addCriterion("resource_type <", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("resource_type <=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIn(List<Integer> values) {
            addCriterion("resource_type in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotIn(List<Integer> values) {
            addCriterion("resource_type not in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("resource_type between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("resource_type not between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceRankIsNull() {
            addCriterion("resource_rank is null");
            return (Criteria) this;
        }

        public Criteria andResourceRankIsNotNull() {
            addCriterion("resource_rank is not null");
            return (Criteria) this;
        }

        public Criteria andResourceRankEqualTo(Integer value) {
            addCriterion("resource_rank =", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankNotEqualTo(Integer value) {
            addCriterion("resource_rank <>", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankGreaterThan(Integer value) {
            addCriterion("resource_rank >", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("resource_rank >=", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankLessThan(Integer value) {
            addCriterion("resource_rank <", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankLessThanOrEqualTo(Integer value) {
            addCriterion("resource_rank <=", value, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankIn(List<Integer> values) {
            addCriterion("resource_rank in", values, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankNotIn(List<Integer> values) {
            addCriterion("resource_rank not in", values, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankBetween(Integer value1, Integer value2) {
            addCriterion("resource_rank between", value1, value2, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceRankNotBetween(Integer value1, Integer value2) {
            addCriterion("resource_rank not between", value1, value2, "resourceRank");
            return (Criteria) this;
        }

        public Criteria andResourceIndexIsNull() {
            addCriterion("resource_index is null");
            return (Criteria) this;
        }

        public Criteria andResourceIndexIsNotNull() {
            addCriterion("resource_index is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIndexEqualTo(Integer value) {
            addCriterion("resource_index =", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexNotEqualTo(Integer value) {
            addCriterion("resource_index <>", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexGreaterThan(Integer value) {
            addCriterion("resource_index >", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("resource_index >=", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexLessThan(Integer value) {
            addCriterion("resource_index <", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexLessThanOrEqualTo(Integer value) {
            addCriterion("resource_index <=", value, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexIn(List<Integer> values) {
            addCriterion("resource_index in", values, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexNotIn(List<Integer> values) {
            addCriterion("resource_index not in", values, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexBetween(Integer value1, Integer value2) {
            addCriterion("resource_index between", value1, value2, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("resource_index not between", value1, value2, "resourceIndex");
            return (Criteria) this;
        }

        public Criteria andResourceStatusIsNull() {
            addCriterion("resource_status is null");
            return (Criteria) this;
        }

        public Criteria andResourceStatusIsNotNull() {
            addCriterion("resource_status is not null");
            return (Criteria) this;
        }

        public Criteria andResourceStatusEqualTo(Integer value) {
            addCriterion("resource_status =", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusNotEqualTo(Integer value) {
            addCriterion("resource_status <>", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusGreaterThan(Integer value) {
            addCriterion("resource_status >", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("resource_status >=", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusLessThan(Integer value) {
            addCriterion("resource_status <", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusLessThanOrEqualTo(Integer value) {
            addCriterion("resource_status <=", value, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusIn(List<Integer> values) {
            addCriterion("resource_status in", values, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusNotIn(List<Integer> values) {
            addCriterion("resource_status not in", values, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusBetween(Integer value1, Integer value2) {
            addCriterion("resource_status between", value1, value2, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("resource_status not between", value1, value2, "resourceStatus");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeIsNull() {
            addCriterion("resource_create_time is null");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeIsNotNull() {
            addCriterion("resource_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeEqualTo(Date value) {
            addCriterion("resource_create_time =", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeNotEqualTo(Date value) {
            addCriterion("resource_create_time <>", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeGreaterThan(Date value) {
            addCriterion("resource_create_time >", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resource_create_time >=", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeLessThan(Date value) {
            addCriterion("resource_create_time <", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("resource_create_time <=", value, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeIn(List<Date> values) {
            addCriterion("resource_create_time in", values, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeNotIn(List<Date> values) {
            addCriterion("resource_create_time not in", values, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeBetween(Date value1, Date value2) {
            addCriterion("resource_create_time between", value1, value2, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("resource_create_time not between", value1, value2, "resourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdIsNull() {
            addCriterion("resource_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdIsNotNull() {
            addCriterion("resource_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdEqualTo(String value) {
            addCriterion("resource_create_user_id =", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdNotEqualTo(String value) {
            addCriterion("resource_create_user_id <>", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdGreaterThan(String value) {
            addCriterion("resource_create_user_id >", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("resource_create_user_id >=", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdLessThan(String value) {
            addCriterion("resource_create_user_id <", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("resource_create_user_id <=", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdLike(String value) {
            addCriterion("resource_create_user_id like", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdNotLike(String value) {
            addCriterion("resource_create_user_id not like", value, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdIn(List<String> values) {
            addCriterion("resource_create_user_id in", values, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdNotIn(List<String> values) {
            addCriterion("resource_create_user_id not in", values, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdBetween(String value1, String value2) {
            addCriterion("resource_create_user_id between", value1, value2, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("resource_create_user_id not between", value1, value2, "resourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeIsNull() {
            addCriterion("resource_update_time is null");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeIsNotNull() {
            addCriterion("resource_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeEqualTo(Date value) {
            addCriterion("resource_update_time =", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeNotEqualTo(Date value) {
            addCriterion("resource_update_time <>", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeGreaterThan(Date value) {
            addCriterion("resource_update_time >", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resource_update_time >=", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeLessThan(Date value) {
            addCriterion("resource_update_time <", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("resource_update_time <=", value, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeIn(List<Date> values) {
            addCriterion("resource_update_time in", values, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeNotIn(List<Date> values) {
            addCriterion("resource_update_time not in", values, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("resource_update_time between", value1, value2, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("resource_update_time not between", value1, value2, "resourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdIsNull() {
            addCriterion("resource_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdIsNotNull() {
            addCriterion("resource_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdEqualTo(String value) {
            addCriterion("resource_update_user_id =", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdNotEqualTo(String value) {
            addCriterion("resource_update_user_id <>", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdGreaterThan(String value) {
            addCriterion("resource_update_user_id >", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("resource_update_user_id >=", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdLessThan(String value) {
            addCriterion("resource_update_user_id <", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("resource_update_user_id <=", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdLike(String value) {
            addCriterion("resource_update_user_id like", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdNotLike(String value) {
            addCriterion("resource_update_user_id not like", value, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdIn(List<String> values) {
            addCriterion("resource_update_user_id in", values, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdNotIn(List<String> values) {
            addCriterion("resource_update_user_id not in", values, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdBetween(String value1, String value2) {
            addCriterion("resource_update_user_id between", value1, value2, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("resource_update_user_id not between", value1, value2, "resourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteIsNull() {
            addCriterion("resource_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteIsNotNull() {
            addCriterion("resource_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteEqualTo(Boolean value) {
            addCriterion("resource_is_delete =", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteNotEqualTo(Boolean value) {
            addCriterion("resource_is_delete <>", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteGreaterThan(Boolean value) {
            addCriterion("resource_is_delete >", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("resource_is_delete >=", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteLessThan(Boolean value) {
            addCriterion("resource_is_delete <", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("resource_is_delete <=", value, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteIn(List<Boolean> values) {
            addCriterion("resource_is_delete in", values, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteNotIn(List<Boolean> values) {
            addCriterion("resource_is_delete not in", values, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("resource_is_delete between", value1, value2, "resourceIsDelete");
            return (Criteria) this;
        }

        public Criteria andResourceIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("resource_is_delete not between", value1, value2, "resourceIsDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   resource
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   resource
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}