package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleResourceExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table role_resource
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table role_resource
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table role_resource
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public RoleResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   role_resource
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoleResourceRoleIdIsNull() {
            addCriterion("role_resource_role_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdIsNotNull() {
            addCriterion("role_resource_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdEqualTo(String value) {
            addCriterion("role_resource_role_id =", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdNotEqualTo(String value) {
            addCriterion("role_resource_role_id <>", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdGreaterThan(String value) {
            addCriterion("role_resource_role_id >", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_resource_role_id >=", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdLessThan(String value) {
            addCriterion("role_resource_role_id <", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdLessThanOrEqualTo(String value) {
            addCriterion("role_resource_role_id <=", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdLike(String value) {
            addCriterion("role_resource_role_id like", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdNotLike(String value) {
            addCriterion("role_resource_role_id not like", value, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdIn(List<String> values) {
            addCriterion("role_resource_role_id in", values, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdNotIn(List<String> values) {
            addCriterion("role_resource_role_id not in", values, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdBetween(String value1, String value2) {
            addCriterion("role_resource_role_id between", value1, value2, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceRoleIdNotBetween(String value1, String value2) {
            addCriterion("role_resource_role_id not between", value1, value2, "roleResourceRoleId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdIsNull() {
            addCriterion("role_resource_resource_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdIsNotNull() {
            addCriterion("role_resource_resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdEqualTo(String value) {
            addCriterion("role_resource_resource_id =", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdNotEqualTo(String value) {
            addCriterion("role_resource_resource_id <>", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdGreaterThan(String value) {
            addCriterion("role_resource_resource_id >", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_resource_resource_id >=", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdLessThan(String value) {
            addCriterion("role_resource_resource_id <", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdLessThanOrEqualTo(String value) {
            addCriterion("role_resource_resource_id <=", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdLike(String value) {
            addCriterion("role_resource_resource_id like", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdNotLike(String value) {
            addCriterion("role_resource_resource_id not like", value, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdIn(List<String> values) {
            addCriterion("role_resource_resource_id in", values, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdNotIn(List<String> values) {
            addCriterion("role_resource_resource_id not in", values, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdBetween(String value1, String value2) {
            addCriterion("role_resource_resource_id between", value1, value2, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceResourceIdNotBetween(String value1, String value2) {
            addCriterion("role_resource_resource_id not between", value1, value2, "roleResourceResourceId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeIsNull() {
            addCriterion("role_resource_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeIsNotNull() {
            addCriterion("role_resource_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeEqualTo(Date value) {
            addCriterion("role_resource_create_time =", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeNotEqualTo(Date value) {
            addCriterion("role_resource_create_time <>", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeGreaterThan(Date value) {
            addCriterion("role_resource_create_time >", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_resource_create_time >=", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeLessThan(Date value) {
            addCriterion("role_resource_create_time <", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("role_resource_create_time <=", value, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeIn(List<Date> values) {
            addCriterion("role_resource_create_time in", values, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeNotIn(List<Date> values) {
            addCriterion("role_resource_create_time not in", values, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeBetween(Date value1, Date value2) {
            addCriterion("role_resource_create_time between", value1, value2, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("role_resource_create_time not between", value1, value2, "roleResourceCreateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdIsNull() {
            addCriterion("role_resource_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdIsNotNull() {
            addCriterion("role_resource_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdEqualTo(String value) {
            addCriterion("role_resource_create_user_id =", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdNotEqualTo(String value) {
            addCriterion("role_resource_create_user_id <>", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdGreaterThan(String value) {
            addCriterion("role_resource_create_user_id >", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_resource_create_user_id >=", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdLessThan(String value) {
            addCriterion("role_resource_create_user_id <", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("role_resource_create_user_id <=", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdLike(String value) {
            addCriterion("role_resource_create_user_id like", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdNotLike(String value) {
            addCriterion("role_resource_create_user_id not like", value, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdIn(List<String> values) {
            addCriterion("role_resource_create_user_id in", values, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdNotIn(List<String> values) {
            addCriterion("role_resource_create_user_id not in", values, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdBetween(String value1, String value2) {
            addCriterion("role_resource_create_user_id between", value1, value2, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("role_resource_create_user_id not between", value1, value2, "roleResourceCreateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeIsNull() {
            addCriterion("role_resource_update_time is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeIsNotNull() {
            addCriterion("role_resource_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeEqualTo(Date value) {
            addCriterion("role_resource_update_time =", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeNotEqualTo(Date value) {
            addCriterion("role_resource_update_time <>", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeGreaterThan(Date value) {
            addCriterion("role_resource_update_time >", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("role_resource_update_time >=", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeLessThan(Date value) {
            addCriterion("role_resource_update_time <", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("role_resource_update_time <=", value, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeIn(List<Date> values) {
            addCriterion("role_resource_update_time in", values, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeNotIn(List<Date> values) {
            addCriterion("role_resource_update_time not in", values, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("role_resource_update_time between", value1, value2, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("role_resource_update_time not between", value1, value2, "roleResourceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdIsNull() {
            addCriterion("role_resource_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdIsNotNull() {
            addCriterion("role_resource_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdEqualTo(String value) {
            addCriterion("role_resource_update_user_id =", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdNotEqualTo(String value) {
            addCriterion("role_resource_update_user_id <>", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdGreaterThan(String value) {
            addCriterion("role_resource_update_user_id >", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("role_resource_update_user_id >=", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdLessThan(String value) {
            addCriterion("role_resource_update_user_id <", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("role_resource_update_user_id <=", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdLike(String value) {
            addCriterion("role_resource_update_user_id like", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdNotLike(String value) {
            addCriterion("role_resource_update_user_id not like", value, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdIn(List<String> values) {
            addCriterion("role_resource_update_user_id in", values, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdNotIn(List<String> values) {
            addCriterion("role_resource_update_user_id not in", values, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdBetween(String value1, String value2) {
            addCriterion("role_resource_update_user_id between", value1, value2, "roleResourceUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andRoleResourceUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("role_resource_update_user_id not between", value1, value2, "roleResourceUpdateUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   role_resource
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   role_resource
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}