package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SequenceExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sequence
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sequence
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table sequence
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public SequenceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   sequence
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSequenceIdIsNull() {
            addCriterion("sequence_id is null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIsNotNull() {
            addCriterion("sequence_id is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceIdEqualTo(Integer value) {
            addCriterion("sequence_id =", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotEqualTo(Integer value) {
            addCriterion("sequence_id <>", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThan(Integer value) {
            addCriterion("sequence_id >", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sequence_id >=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThan(Integer value) {
            addCriterion("sequence_id <", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdLessThanOrEqualTo(Integer value) {
            addCriterion("sequence_id <=", value, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdIn(List<Integer> values) {
            addCriterion("sequence_id in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotIn(List<Integer> values) {
            addCriterion("sequence_id not in", values, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdBetween(Integer value1, Integer value2) {
            addCriterion("sequence_id between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sequence_id not between", value1, value2, "sequenceId");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIsNull() {
            addCriterion("sequence_name is null");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIsNotNull() {
            addCriterion("sequence_name is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceNameEqualTo(String value) {
            addCriterion("sequence_name =", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotEqualTo(String value) {
            addCriterion("sequence_name <>", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameGreaterThan(String value) {
            addCriterion("sequence_name >", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameGreaterThanOrEqualTo(String value) {
            addCriterion("sequence_name >=", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLessThan(String value) {
            addCriterion("sequence_name <", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLessThanOrEqualTo(String value) {
            addCriterion("sequence_name <=", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameLike(String value) {
            addCriterion("sequence_name like", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotLike(String value) {
            addCriterion("sequence_name not like", value, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameIn(List<String> values) {
            addCriterion("sequence_name in", values, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotIn(List<String> values) {
            addCriterion("sequence_name not in", values, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameBetween(String value1, String value2) {
            addCriterion("sequence_name between", value1, value2, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceNameNotBetween(String value1, String value2) {
            addCriterion("sequence_name not between", value1, value2, "sequenceName");
            return (Criteria) this;
        }

        public Criteria andSequenceDescIsNull() {
            addCriterion("sequence_desc is null");
            return (Criteria) this;
        }

        public Criteria andSequenceDescIsNotNull() {
            addCriterion("sequence_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceDescEqualTo(String value) {
            addCriterion("sequence_desc =", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescNotEqualTo(String value) {
            addCriterion("sequence_desc <>", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescGreaterThan(String value) {
            addCriterion("sequence_desc >", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescGreaterThanOrEqualTo(String value) {
            addCriterion("sequence_desc >=", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescLessThan(String value) {
            addCriterion("sequence_desc <", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescLessThanOrEqualTo(String value) {
            addCriterion("sequence_desc <=", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescLike(String value) {
            addCriterion("sequence_desc like", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescNotLike(String value) {
            addCriterion("sequence_desc not like", value, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescIn(List<String> values) {
            addCriterion("sequence_desc in", values, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescNotIn(List<String> values) {
            addCriterion("sequence_desc not in", values, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescBetween(String value1, String value2) {
            addCriterion("sequence_desc between", value1, value2, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceDescNotBetween(String value1, String value2) {
            addCriterion("sequence_desc not between", value1, value2, "sequenceDesc");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeIsNull() {
            addCriterion("sequence_create_time is null");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeIsNotNull() {
            addCriterion("sequence_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeEqualTo(Date value) {
            addCriterion("sequence_create_time =", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeNotEqualTo(Date value) {
            addCriterion("sequence_create_time <>", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeGreaterThan(Date value) {
            addCriterion("sequence_create_time >", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sequence_create_time >=", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeLessThan(Date value) {
            addCriterion("sequence_create_time <", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("sequence_create_time <=", value, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeIn(List<Date> values) {
            addCriterion("sequence_create_time in", values, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeNotIn(List<Date> values) {
            addCriterion("sequence_create_time not in", values, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeBetween(Date value1, Date value2) {
            addCriterion("sequence_create_time between", value1, value2, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("sequence_create_time not between", value1, value2, "sequenceCreateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeIsNull() {
            addCriterion("sequence_update_time is null");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeIsNotNull() {
            addCriterion("sequence_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeEqualTo(Date value) {
            addCriterion("sequence_update_time =", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeNotEqualTo(Date value) {
            addCriterion("sequence_update_time <>", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeGreaterThan(Date value) {
            addCriterion("sequence_update_time >", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sequence_update_time >=", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeLessThan(Date value) {
            addCriterion("sequence_update_time <", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("sequence_update_time <=", value, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeIn(List<Date> values) {
            addCriterion("sequence_update_time in", values, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeNotIn(List<Date> values) {
            addCriterion("sequence_update_time not in", values, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("sequence_update_time between", value1, value2, "sequenceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andSequenceUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("sequence_update_time not between", value1, value2, "sequenceUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   sequence
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   sequence
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}