package com.dllg.ebpay.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TeamExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table team
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table team
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table team
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public TeamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   team
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTeamIdIsNull() {
            addCriterion("team_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNotNull() {
            addCriterion("team_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamIdEqualTo(String value) {
            addCriterion("team_id =", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotEqualTo(String value) {
            addCriterion("team_id <>", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThan(String value) {
            addCriterion("team_id >", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("team_id >=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThan(String value) {
            addCriterion("team_id <", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThanOrEqualTo(String value) {
            addCriterion("team_id <=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLike(String value) {
            addCriterion("team_id like", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotLike(String value) {
            addCriterion("team_id not like", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIn(List<String> values) {
            addCriterion("team_id in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotIn(List<String> values) {
            addCriterion("team_id not in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdBetween(String value1, String value2) {
            addCriterion("team_id between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotBetween(String value1, String value2) {
            addCriterion("team_id not between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdIsNull() {
            addCriterion("team_company_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdIsNotNull() {
            addCriterion("team_company_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdEqualTo(String value) {
            addCriterion("team_company_id =", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdNotEqualTo(String value) {
            addCriterion("team_company_id <>", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdGreaterThan(String value) {
            addCriterion("team_company_id >", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("team_company_id >=", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdLessThan(String value) {
            addCriterion("team_company_id <", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("team_company_id <=", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdLike(String value) {
            addCriterion("team_company_id like", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdNotLike(String value) {
            addCriterion("team_company_id not like", value, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdIn(List<String> values) {
            addCriterion("team_company_id in", values, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdNotIn(List<String> values) {
            addCriterion("team_company_id not in", values, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdBetween(String value1, String value2) {
            addCriterion("team_company_id between", value1, value2, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamCompanyIdNotBetween(String value1, String value2) {
            addCriterion("team_company_id not between", value1, value2, "teamCompanyId");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNull() {
            addCriterion("team_name is null");
            return (Criteria) this;
        }

        public Criteria andTeamNameIsNotNull() {
            addCriterion("team_name is not null");
            return (Criteria) this;
        }

        public Criteria andTeamNameEqualTo(String value) {
            addCriterion("team_name =", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotEqualTo(String value) {
            addCriterion("team_name <>", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThan(String value) {
            addCriterion("team_name >", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameGreaterThanOrEqualTo(String value) {
            addCriterion("team_name >=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThan(String value) {
            addCriterion("team_name <", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLessThanOrEqualTo(String value) {
            addCriterion("team_name <=", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameLike(String value) {
            addCriterion("team_name like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotLike(String value) {
            addCriterion("team_name not like", value, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameIn(List<String> values) {
            addCriterion("team_name in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotIn(List<String> values) {
            addCriterion("team_name not in", values, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameBetween(String value1, String value2) {
            addCriterion("team_name between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamNameNotBetween(String value1, String value2) {
            addCriterion("team_name not between", value1, value2, "teamName");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIsNull() {
            addCriterion("team_type is null");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIsNotNull() {
            addCriterion("team_type is not null");
            return (Criteria) this;
        }

        public Criteria andTeamTypeEqualTo(Integer value) {
            addCriterion("team_type =", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotEqualTo(Integer value) {
            addCriterion("team_type <>", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeGreaterThan(Integer value) {
            addCriterion("team_type >", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("team_type >=", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeLessThan(Integer value) {
            addCriterion("team_type <", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeLessThanOrEqualTo(Integer value) {
            addCriterion("team_type <=", value, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeIn(List<Integer> values) {
            addCriterion("team_type in", values, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotIn(List<Integer> values) {
            addCriterion("team_type not in", values, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeBetween(Integer value1, Integer value2) {
            addCriterion("team_type between", value1, value2, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("team_type not between", value1, value2, "teamType");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkIsNull() {
            addCriterion("team_remark is null");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkIsNotNull() {
            addCriterion("team_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkEqualTo(String value) {
            addCriterion("team_remark =", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkNotEqualTo(String value) {
            addCriterion("team_remark <>", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkGreaterThan(String value) {
            addCriterion("team_remark >", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("team_remark >=", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkLessThan(String value) {
            addCriterion("team_remark <", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkLessThanOrEqualTo(String value) {
            addCriterion("team_remark <=", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkLike(String value) {
            addCriterion("team_remark like", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkNotLike(String value) {
            addCriterion("team_remark not like", value, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkIn(List<String> values) {
            addCriterion("team_remark in", values, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkNotIn(List<String> values) {
            addCriterion("team_remark not in", values, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkBetween(String value1, String value2) {
            addCriterion("team_remark between", value1, value2, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamRemarkNotBetween(String value1, String value2) {
            addCriterion("team_remark not between", value1, value2, "teamRemark");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIsNull() {
            addCriterion("team_create_time is null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIsNotNull() {
            addCriterion("team_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeEqualTo(Date value) {
            addCriterion("team_create_time =", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotEqualTo(Date value) {
            addCriterion("team_create_time <>", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeGreaterThan(Date value) {
            addCriterion("team_create_time >", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("team_create_time >=", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeLessThan(Date value) {
            addCriterion("team_create_time <", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("team_create_time <=", value, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeIn(List<Date> values) {
            addCriterion("team_create_time in", values, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotIn(List<Date> values) {
            addCriterion("team_create_time not in", values, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeBetween(Date value1, Date value2) {
            addCriterion("team_create_time between", value1, value2, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("team_create_time not between", value1, value2, "teamCreateTime");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdIsNull() {
            addCriterion("team_create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdIsNotNull() {
            addCriterion("team_create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdEqualTo(String value) {
            addCriterion("team_create_user_id =", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdNotEqualTo(String value) {
            addCriterion("team_create_user_id <>", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdGreaterThan(String value) {
            addCriterion("team_create_user_id >", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("team_create_user_id >=", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdLessThan(String value) {
            addCriterion("team_create_user_id <", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("team_create_user_id <=", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdLike(String value) {
            addCriterion("team_create_user_id like", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdNotLike(String value) {
            addCriterion("team_create_user_id not like", value, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdIn(List<String> values) {
            addCriterion("team_create_user_id in", values, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdNotIn(List<String> values) {
            addCriterion("team_create_user_id not in", values, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdBetween(String value1, String value2) {
            addCriterion("team_create_user_id between", value1, value2, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("team_create_user_id not between", value1, value2, "teamCreateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeIsNull() {
            addCriterion("team_update_time is null");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeIsNotNull() {
            addCriterion("team_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeEqualTo(Date value) {
            addCriterion("team_update_time =", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeNotEqualTo(Date value) {
            addCriterion("team_update_time <>", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeGreaterThan(Date value) {
            addCriterion("team_update_time >", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("team_update_time >=", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeLessThan(Date value) {
            addCriterion("team_update_time <", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("team_update_time <=", value, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeIn(List<Date> values) {
            addCriterion("team_update_time in", values, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeNotIn(List<Date> values) {
            addCriterion("team_update_time not in", values, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("team_update_time between", value1, value2, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("team_update_time not between", value1, value2, "teamUpdateTime");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdIsNull() {
            addCriterion("team_update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdIsNotNull() {
            addCriterion("team_update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdEqualTo(String value) {
            addCriterion("team_update_user_id =", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdNotEqualTo(String value) {
            addCriterion("team_update_user_id <>", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdGreaterThan(String value) {
            addCriterion("team_update_user_id >", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("team_update_user_id >=", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdLessThan(String value) {
            addCriterion("team_update_user_id <", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("team_update_user_id <=", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdLike(String value) {
            addCriterion("team_update_user_id like", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdNotLike(String value) {
            addCriterion("team_update_user_id not like", value, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdIn(List<String> values) {
            addCriterion("team_update_user_id in", values, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdNotIn(List<String> values) {
            addCriterion("team_update_user_id not in", values, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdBetween(String value1, String value2) {
            addCriterion("team_update_user_id between", value1, value2, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("team_update_user_id not between", value1, value2, "teamUpdateUserId");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteIsNull() {
            addCriterion("team_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteIsNotNull() {
            addCriterion("team_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteEqualTo(Boolean value) {
            addCriterion("team_is_delete =", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteNotEqualTo(Boolean value) {
            addCriterion("team_is_delete <>", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteGreaterThan(Boolean value) {
            addCriterion("team_is_delete >", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("team_is_delete >=", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteLessThan(Boolean value) {
            addCriterion("team_is_delete <", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("team_is_delete <=", value, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteIn(List<Boolean> values) {
            addCriterion("team_is_delete in", values, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteNotIn(List<Boolean> values) {
            addCriterion("team_is_delete not in", values, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("team_is_delete between", value1, value2, "teamIsDelete");
            return (Criteria) this;
        }

        public Criteria andTeamIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("team_is_delete not between", value1, value2, "teamIsDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   team
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   team
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}